### ISSUE TITLE
(Ability to) disable verbose output

### ISSUE THREAD

**Issue by AirOnSkin** [ansible/ansible-lint-action#132]
Hello there 🙂 

I've noticed that ansible-lint is always executed with `-vvv` when run with the GH action.
Since verbosity can be controlled by the [ansible-lint config file](https://ansible-lint.readthedocs.io/configuring/), I'd very much like this to be removed or to have an option to disable verbose output for the action.

Do you think that's possible?

**Comment by geerlingguy** [comment]
I'm in agreement; if you need the verbosity, you can enable it via the config file; by default the regular verbosity would be preferred.

**Comment by leovct** [comment]
Same here, is there any work-around?
