### ISSUE TITLE
Repository not found: ansible-community/ansible-lint-action

### ISSUE THREAD

**Issue by manelsanchez-scopely** [ansible/ansible-lint-action#134]
Since last Friday we are facing next error: 
"Unable to resolve actions. Repository not found: ansible-community/ansible-lint-action."
If I point to ansible/ansible-lint-action the action run's without problems.

It could be that this repo is deleted or moved from ansible-community to ansible?
It troubles me that I cannot see any reference about this change...

Thanks in advance

**Comment by ssbarnea** [comment]
Not sure why the implicit redirect no longer works for you but the fix is to make use of current URL: ansible/ansible-lint-action
