### ISSUE TITLE
ansible-lint v4.2.0

### ISSUE THREAD

**Issue by xUnholy** [ansible/ansible-lint-action#16]
I'm running locally version v4.2.0 however my CI is only running version 4.1.0 - documentation says I can specify tags, and versions, is that from this repository or the upstream ansible-lint repo?

**Comment by webknjaz** [comment]
GitHub Actions are bound to repos so anything you specify (tags, branches, commit hashes) has to exist in this repo.

**Comment by xUnholy** [comment]
Thanks for clarifying @webknjaz. Seeing as that is the case could we create some GitHub action scheduler that checks the upstream for new releases and when a new release is made this repo can have the version changes reflected.

I noticed there is a branch with some proposed versioning and I think that would be a good idea.

**Comment by webknjaz** [comment]
Well, it's not just tags, Dockerfile will need to be changed every time.

**Comment by xUnholy** [comment]
Why not allow the Dockerfile to accept the version as a --build-arg so the version can be passed as an arg rather than a hard coded value.

**Comment by webknjaz** [comment]
Because there's no interface for supplying build args in GitHub Actions. We don't pre-build the image, GitHub Workflows do the build when they run Actions.

**Comment by xUnholy** [comment]
I'm happy to go with what ever approach you choose, I'm just after the ability to pin to a specific version and I think there should be a simple method of keeping parity with the upstream version without requiring manual intervention.

**Comment by webknjaz** [comment]
If you want to explore this, go ahead. I don't have resources to figure this out right now.

**Comment by webknjaz** [comment]
I guess the shell script could support an input arg for extra deps and users could specify some things to `pip install` on top.

**Comment by xUnholy** [comment]
@webknjaz correct, that would be perhaps the best option, rather than install in the Dockerfile allow the entry point to do the installation and have the version as an input arg - sounds good to me. I'll raise a PR when I get a chance :+1:
