### ISSUE TITLE
Link to github marketplace is broken

### ISSUE THREAD

**Issue by hfrSchmidt** [ansible/ansible-lint-action#170]
The link to the github marketplace site of the action is broken. Also I seem to be unable to find the action, when I search for it on github marketplace. 
Did this change deliberately?

**Comment by ssbarnea** [comment]
That was a side effect from some reconfiguration we were attempting and we opened a ticket about 10 days ago but github folks told use that they need help from their engineering. 

Treat unlisting from marketplace as a temporary issue, it does not affect anyone already using it or wanting to use the action. Basically marketplace is just a "directory" that makes searching for actions easier.

Our plan is to move the action directly into ansible-lint repository, which will make the update on a new version instantly available for everyone. I will add more details here once I get them.

**Comment by hfrSchmidt** [comment]
Thanks for the reply! Integrating updates from ansible-lint into the action directly sounds very nice, since we are currently having problems in our gh CI due to a bug in 6.12.1. Looking forward to it!
