### ISSUE TITLE
add option to test against older ansible versions

### ISSUE THREAD

**Issue by ahmadalli** [ansible/ansible-lint-action#19]
is it possible to test a playbook with older ansible versions and make sure the playlist is compatible with them or not? for example `exit_host` is added to ansible 2.8's `meta` module and fails on older ansible versions

**Comment by webknjaz** [comment]
You're basically asking for the possibility to install extra packages in the container in runtime.

I think it's a duplicate of #8

**Comment by xUnholy** [comment]
@ahmadalli there is a pull request that would allow you to test with pinned versions #17 

While this PR is pending I've got a forked version with this capability here: https://github.com/xUnholy/ansible-lint-action

**Comment by ahmadalli** [comment]
@xUnholy thanks :)

**Comment by webknjaz** [comment]
@ahmadalli that's now in master.

**Comment by ahmadalli** [comment]
thanks :)

**Comment by ahmadalli** [comment]
thanks :)
