### ISSUE TITLE
Did something change recently?

### ISSUE THREAD

**Issue by johnpetersjr** [ansible/ansible-lint-action#20]
Been using this for a while, and now suddenly today getting this error on ansible lint checks during my GitHub action check:
```python-traceback
+ ansible-lint -v --force-color '' 'devel/my_yaml_file.yml'
Traceback (most recent call last):
  File "/usr/local/bin/ansible-lint", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/ansiblelint/__main__.py", line 187, in main
    matches.extend(runner.run())
  File "/usr/local/lib/python3.8/site-packages/ansiblelint/__init__.py", line 263, in run
    files.append({'path': ansiblelint.utils.normpath(playbook[0]), 'type': playbook[1]})
  File "/usr/local/lib/python3.8/site-packages/ansiblelint/utils.py", line 725, in normpath
    return os.path.relpath(str(path))
  File "/usr/local/lib/python3.8/posixpath.py", line 453, in relpath
    raise ValueError("no path specified")
ValueError: no path specified
```

**Comment by johnpetersjr** [comment]
Here's my workflow:

---
name: Ansible Lint
on: [pull_request]
jobs:
  linting_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint-action@master
        with:
          targets: |
            devel/my_yaml_file.yml

**Comment by webknjaz** [comment]
Yeah, I think it may be related to https://github.com/ansible/ansible-lint-action/commit/ce0c313e3b344142eb26fa97ee615eca79472220#diff-b958f585a04af5ee2087610ea7180f34R86.

/cc @xUnholy ^

**Comment by DO1JLR** [comment]
I already mentioned something like that at https://github.com/ansible/ansible-lint-action/pull/17#discussion_r399173027

The problem here is the quoted empty ``"$opts"`` variable.

**Comment by DO1JLR** [comment]
And @webknjaz and @xUnholy talked about it here: https://github.com/ansible/ansible-lint-action/pull/17#discussion_r399293346

**Comment by johnpetersjr** [comment]
Seems like now when I specify targets, it is not finding my target playbook.

Strange.  Let me try and figure it out.

**Comment by webknjaz** [comment]
I'm pretty sure it's the same issue. Those quotes would need to be reverted too.

**Comment by webknjaz** [comment]
Reverted.

**Comment by johnpetersjr** [comment]
Same thing is happening with opts as well.
```
+ args=("$@")
+ '[' /entrypoint.sh = /entrypoint.sh ']'
+ echo -E '\nRunning Ansible Lint...\n'
\nRunning Ansible Lint...\n
+ ansible::lint '-x 204'
+ : 'my_yaml_file.yml
'
+ : /github/workspace
+ pushd /github/workspace
+ local opts
++ parse_args '-x 204'
++ local opts=
++ ((  1  ))
++ case "$1" in
++ echo 'ERROR: Unsupported flag: '\''-x 204'\'''
ERROR: Unsupported flag: '-x 204'
++ exit 1
+ opts=
/github/workspace /github/workspace

```

**Comment by moodys-vargav** [comment]
> 
> 
> Same thing is happening with opts as well.
> 
> ```
> + args=("$@")
> + '[' /entrypoint.sh = /entrypoint.sh ']'
> + echo -E '\nRunning Ansible Lint...\n'
> \nRunning Ansible Lint...\n
> + ansible::lint '-x 204'
> + : 'my_yaml_file.yml
> '
> + : /github/workspace
> + pushd /github/workspace
> + local opts
> ++ parse_args '-x 204'
> ++ local opts=
> ++ ((  1  ))
> ++ case "$1" in
> ++ echo 'ERROR: Unsupported flag: '\''-x 204'\'''
> ERROR: Unsupported flag: '-x 204'
> ++ exit 1
> + opts=
> /github/workspace /github/workspace
> ```

That is because of this commit:
54851ed1c0f4328cd05e5531a48c6c385117fd2e
