### ISSUE TITLE
Provide built image so that users don't have to build it for every commit

### ISSUE THREAD

**Issue by lpenz** [ansible/ansible-lint-action#36]

**Comment by lpenz** [comment]
Github actions can use a URL with docker:// prefix to download built images from hub.docker.com.
Doing that would make actions run faster by bypassing building the image during the action.

**Comment by j0holo** [comment]
Great idea, does the Ansible team/maintainers want to host their own image on Docker hub or can we use an already existing one by a third party?

**Comment by lpenz** [comment]
I think the Dockerfile already present in this repository works fine.

**Comment by j0holo** [comment]
I get that, but the build image needs to be stored somewhere right? We could use the GitHub registry which is free but not usable for commonly used Action. Docker hub is an obvious choice, but then who will host it?

**Comment by adamrushuk** [comment]
@lpenz I'm interested in hearing more on this.

Looking through the documentation, do you mean change this line: https://github.com/ansible/ansible-lint-action/blob/master/action.yml#L45

to `image: 'docker://<DOCKER_IMAGE>:<TAG>'`

as per this example? https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/metadata-syntax-for-github-actions#example-using-public-docker-registry-container

**Comment by lpenz** [comment]
That line is fine

What we need to change is the retrieval of the arguments - they have to be obtained from environment variables. I did that in here:
https://github.com/lpenz/ansible-lint-action/commit/fd26cb9c8e347f963a9bfbbaec6f3755b7697dda
(I can make a pull request if people want)

After that, whoever owns the "ansible" user in hub.docker.com should set it up to build the image from this repository, "latest" from master and tag versions seems appropriate.

You can then use the image by specifying `- uses: docker://ansible/ansible-lint-action:VERSION` in a github workflow. The workflow will just download the image from hub.docker.com instead of building it every time.

**Comment by adamrushuk** [comment]
That would be great if the repo owners could implement similar so we wouldn't have to build every time. 👍🏼

**Comment by danielkubat** [comment]
> You can then use the image by specifying `- uses: docker://ansible/ansible-lint-action:VERSION` in a github workflow. The workflow will just download the image from hub.docker.com instead of building it every time.

I second that, especially when Ansible has already user on Docker hub with an images. (https://hub.docker.com/u/ansible). Based on my experience, building of Docker image every time consumes about 80-90% of entire GH Action runtime.

**Comment by cognifloyd** [comment]
According to https://github.com/actions/virtual-environments/issues/1445#issuecomment-713861495
> For publicly accessible containers we are working with docker hub to make sure you will not be impacted by the new rate limits. If you need private containers we still do not have a solution for that problem for forks of public repos.

So, relying on docker hub should not hit rate limiting in github actions (at least for public repos). :)

**Comment by cognifloyd** [comment]
I asked on #ansible-devel about who can get this onto dockerhub and I got two responses:

> ***sivel wonders why ansible-lint hasn't been moved out of the ansible org yet...
> sivel: Should have been done a while ago

> zbr: molecule container includes ansible-lint, https://github.com/ansible-community/molecule-dist
> cognifloyd: Is that on dockerhub?
> tadeboro: My guess would be quay.io since most of the semi-official ansible stuff ends up there.
> cognifloyd: this image? https://quay.io/repository/ansible/molecule
> zbr: yes, but i stopped refreshing it two weeks ago, we will restore the build pipelines.

The ansible/molecule container is currently 318.3MB
Another possible container, [yokogawa/ansible-lint](https://hub.docker.com/r/yokogawa/ansible-lint), is 94.98MB.
This uses python:3.8-slim (45MB) and the yokogawa one uses python:3-alpine (17.31MB), so the container could be optimized by using or following the example of the yokogawa container.

**Comment by bluikko** [comment]
@lpenz I would find a PR very helpful, it is very annoying that the action takes 3 minutes in building step...

**Comment by lpenz** [comment]
I've created a PR, here: https://github.com/ansible/ansible-lint-action/pull/44

It's usable with `docker://lpenz/ansible-lint-action:dockeraction`, example: https://github.com/lpenz/ansible-playbooks/blob/ladatest/.github/workflows/main.yml

Result from that example: https://github.com/lpenz/ansible-playbooks/actions/runs/490558134

**Comment by ssbarnea** [comment]
No longer valid for version on main branch, where we use creator-ee container and no longer build our own.
