### ISSUE TITLE
Invalid workflow file

### ISSUE THREAD

**Issue by SturmB** [ansible/ansible-lint-action#42]
Using the recommended `ansible-lint.yml` contents of:

```yaml
- name: ansible-lint
  uses: ansible/ansible-lint-action@v4.1.0.post0
```

results in an immediate error with GitHub Actions:

![image](https://user-images.githubusercontent.com/6216224/100154573-cbc90e00-2e73-11eb-87f4-dd80e44d54ba.png)

**Comment by webknjaz** [comment]
That is just for one step. You still have to define the whole job: the base VM OS, the step to actually checkout your source, the trigger events...

Start learning how the GitHub Actions workflows work somewhere here: https://docs.github.com/en/free-pro-team@latest/actions/quickstart.
