### ISSUE TITLE
Using @master breaks builds

### ISSUE THREAD

**Issue by iranzo** [ansible/ansible-lint-action#47]
I've a repo with ansible-lint action that requires ansible 2.9, using @master breaks the builds to the point that I'm seriously considering removing it.

Using one of the tagged releases ends up in tags being so old that parameters like `targets:` are not valid.

![image](https://user-images.githubusercontent.com/312463/108489034-61244480-72a1-11eb-8d44-4001169cef14.png)

**Comment by iranzo** [comment]
With #23  this could be avoided

**Comment by MeatsMountain** [comment]
> I've a repo with ansible-lint action that requires ansible 2.9, using @master breaks the builds to the point that I'm seriously considering removing it.
> 
> Using one of the tagged releases ends up in tags being so old that parameters like `targets:` are not valid.
> 
> ![image](https://user-images.githubusercontent.com/312463/108489034-61244480-72a1-11eb-8d44-4001169cef14.png)

**Comment by frankhjung** [comment]
The `master` branch has moved to `main`.

**Comment by ssbarnea** [comment]
Closing as the current code on main is very different. Anyone using `@main` will need to update their implementation. I will add a `v6` tag soon too.
