### ISSUE TITLE
HowTo: Adding modules

### ISSUE THREAD

**Issue by frankenstein91** [ansible/ansible-lint-action#52]
We are currently building an ArchLinux installation with Ansible. In the process, we are using this GitHub action to facilitate collaboration.

We are currently getting an error because we are using an "AUR" module (https://github.com/kewlfft/ansible-aur) for Ansible. How can we add this to the linter in the action?

Error msg: https://github.com/frankenstein91/Arch-Ansible-Install/runs/2428321106#step:4:95

**Comment by ssbarnea** [comment]
No longer valid for version on main branch.
