### ISSUE TITLE
ansible-lint 'rich' problem

### ISSUE THREAD

**Issue by srl295** [ansible/ansible-lint-action#59]
Ran into this: ansible-community/ansible-lint#1795

```
Error in "Lint Ansible Playbook": "ImportError: cannot import name 'render_group' from 'rich.console' (/usr/local/lib/python3.8/site-packages/rich/console.py)"
```

Trying to workaround with this: https://github.com/unicode-org/cldr/pull/1683

-----
**update* Success. I was able to workaround with:

```yaml
        override-deps: |
           rich>=9.5.1,<11.0.0
```

**Comment by McPatate** [comment]
Thank you for the workaround !

**Comment by hugovk** [comment]
https://github.com/ansible-community/ansible-lint/issues/1795 has been fixed and released in https://github.com/ansible-community/ansible-lint/releases/tag/v5.3.2.

**Comment by ssbarnea** [comment]
No longer valid for version on main branch.

**Comment by hugovk** [comment]
Thank you! Will there be a tagged version at some point?
