### ISSUE TITLE
[TODO] Figure out what's going on with GitHub Topics

### ISSUE THREAD

**Issue by webknjaz** [ansible/ansible-lint-action#9]
We use topics to mark what this repository is about and make it better discoverable. In particular, `github-action` tag. It used to work like a charm a month ago. Users could click on the specific topic on the repo page and be redirected to the list of **all the repos** with this topic.

So if you look at https://github.com/topics/github-action now, it only shows 8 repositories with no pagination. Most of those with zero or 1 star, no ranking/sorting.

But if you looked there a few weeks ago, you'd see multiple pages of repos there. They were sorted by the number of stars making it easy to reason about their quality and spread. People could see actions that didn't make it to the Marketplace.

@stoe do you have any idea what's up with GitHub Topics now?

**Comment by stoe** [comment]
> @stoe do you have any idea what's up with GitHub Topics now?

@webknjaz, I wasn't aware of that.
Could you open a ticket via https://support.github.com, please.

**Comment by webknjaz** [comment]
No need for this. It looks fixed now.
